### PR TITLE
Preparation for supporting GHC 7.10.1

### PR DESCRIPTION
**Pull request by asr**
I fixed the compilation with GHC 7.10.1 RC3.

### CODE REVIEW

**Comment by edwinb** [comment]
Hi - thanks for this.

I don't actually use epic any more, so I'm just going to merge directly if you're using it and think this is okay :). Hopefully it still works, at least...

**Comment by asr** [comment]
We are using Epic as a back-end for Agda. Thanks for merging the pull request.

After GHC 7.10.1 be released, could you release a new version to Hackage, please.

**Comment by asr** [comment]
@andreasabel Please release a new version to Hackage including this pull request.

**Comment by andreasabel** [comment]
Done.

**Comment by asr** [comment]
Thanks!

**Pull request merged**
